package com.chinamcom.framework.sociality.model;

import java.util.Date;

public class AppFriendship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.UID_0
     *
     * @mbggenerated
     */
    private Integer uid0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.UID_1
     *
     * @mbggenerated
     */
    private Integer uid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.STATUS
     *
     * @mbggenerated
     */
    private Integer status;
    private Integer status1;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.ALIAS_0
     *
     * @mbggenerated
     */
    private String head;
    private String alias0;
    private String username;
    private String aliasname;
    private String headimage;
    private String nickname;
    private String phonenum;
    private String imei;
    private Integer sex;
    private Integer watchstat;
    private Integer wasdeletedfriend;

    
    public Integer getWatchstat() {
		return watchstat;
	}

	public void setWatchstat(Integer watchstat) {
		this.watchstat = watchstat;
	}

	public Integer getStatus1() {
		return status1;
	}

	public void setStatus1(Integer status1) {
		this.status1 = status1;
	}

	public String getImei() {
		return imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getHeadimage() {
		return headimage;
	}

	public void setHeadimage(String headimage) {
		this.headimage = headimage;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPhonenum() {
		return phonenum;
	}

	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getHead() {
		return head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAliasname() {
		return aliasname;
	}

	public void setAliasname(String aliasname) {
		this.aliasname = aliasname;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_friendship.ALIAS_1
     *
     * @mbggenerated
     */
    private String alias1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.ID
     *
     * @return the value of app_friendship.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.ID
     *
     * @param id the value for app_friendship.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.UID_0
     *
     * @return the value of app_friendship.UID_0
     *
     * @mbggenerated
     */
    public Integer getUid0() {
        return uid0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.UID_0
     *
     * @param uid0 the value for app_friendship.UID_0
     *
     * @mbggenerated
     */
    public void setUid0(Integer uid0) {
        this.uid0 = uid0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.UID_1
     *
     * @return the value of app_friendship.UID_1
     *
     * @mbggenerated
     */
    public Integer getUid1() {
        return uid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.UID_1
     *
     * @param uid1 the value for app_friendship.UID_1
     *
     * @mbggenerated
     */
    public void setUid1(Integer uid1) {
        this.uid1 = uid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.STATUS
     *
     * @return the value of app_friendship.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.STATUS
     *
     * @param status the value for app_friendship.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.CREATE_TIME
     *
     * @return the value of app_friendship.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.CREATE_TIME
     *
     * @param createTime the value for app_friendship.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.UPDATE_TIME
     *
     * @return the value of app_friendship.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.UPDATE_TIME
     *
     * @param updateTime the value for app_friendship.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.ALIAS_0
     *
     * @return the value of app_friendship.ALIAS_0
     *
     * @mbggenerated
     */
    public String getAlias0() {
        return alias0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.ALIAS_0
     *
     * @param alias0 the value for app_friendship.ALIAS_0
     *
     * @mbggenerated
     */
    public void setAlias0(String alias0) {
        this.alias0 = alias0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.ALIAS_1
     *
     * @return the value of app_friendship.ALIAS_1
     *
     * @mbggenerated
     */
    public String getAlias1() {
        return alias1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.ALIAS_1
     *
     * @param alias1 the value for app_friendship.ALIAS_1
     *
     * @mbggenerated
     */
    public void setAlias1(String alias1) {
        this.alias1 = alias1;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_friendship.wasdeletedfriend
     *
     * @return the value of app_friendship.wasdeletedfriend
     *
     * @mbggenerated Fri Jan 13 10:53:19 CST 2017
     */
    public Integer getWasdeletedfriend() {
        return wasdeletedfriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_friendship.wasdeletedfriend
     *
     * @param wasdeletedfriend the value for app_friendship.wasdeletedfriend
     *
     * @mbggenerated Fri Jan 13 10:53:19 CST 2017
     */
    public void setWasdeletedfriend(Integer wasdeletedfriend) {
        this.wasdeletedfriend = wasdeletedfriend;
    }
}